{{- $fullName := include "openshift-logforwarding-splunk.fullname" . -}}
{{- $splunkSecret := printf "%s-splunk" $fullName -}}
{{- $logForwardingConfig := printf "%s-config" $fullName -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/component: fluentd
{{ include "openshift-logforwarding-splunk.labels" . | indent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          terminationMessagePath: /dev/termination-log
          name: {{ $fullName }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: fluentd-loglevel
            - name: SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: shared_key
            - name: SPLUNK_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: splunk-hostname
            - name: SPLUNK_SOURCETYPE
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: splunk-sourcetype
            - name: SPLUNK_SOURCE
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: splunk-source
            - name: SPLUNK_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: splunk-port
            - name: SPLUNK_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: splunk-protocol
            - name: SPLUNK_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: splunk-insecure
            - name: SPLUNK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: hec-token
            - name: SPLUNK_INDEX
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: splunk-index
            - name: FLUENTD_SSL_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: fluentd-ssl-passsphrase
          imagePullPolicy: Always
          volumeMounts:
            - name: {{ $logForwardingConfig }}
              readOnly: true
              mountPath: /etc/fluent/
            - mountPath: /secret/fluentd
              name: {{ $fullName }}
              readOnly: true
            {{- if and (not .Values.forwarding.splunk.insecure) .Values.forwarding.splunk.caFile }}
            - mountPath: /secret/splunk
              name: splpunk-certs
              readOnly: true
            {{- end }}
          terminationMessagePolicy: File
          image: {{ .Values.forwarding.fluentd.image }}
          args:
            - scl
            - enable
            - rh-ruby25
            - "--"
            - fluentd
          livenessProbe:
            tcpSocket:
              port: 24224
            periodSeconds: 5
            timeoutSeconds: 3
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 24224
            periodSeconds: 3
            timeoutSeconds: 2
            initialDelaySeconds: 2
          ports:
            - containerPort: 24224
              name: forwarder-tcp
              protocol: TCP
            - containerPort: 24224
              name: forwarder-udp
              protocol: UDP
      serviceAccount: {{ $fullName }}
      volumes:
        - name: {{ $logForwardingConfig }}
          configMap:
            name: {{ $fullName }}
            items:
              - key: td-agent.conf
                path: fluent.conf
            defaultMode: 420
            optional: true
        - name: {{ $fullName }}
          secret:
            secretName: {{ $fullName }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        {{- if and (not .Values.forwarding.splunk.insecure) .Values.forwarding.splunk.caFile }}
        - name: splunk-certs
          secret:
            secretName: {{ $fullName }}-splunk
            items:
              - key: splunk-ca.crt
                path: splunk-ca.crt
        {{- end }}
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
