{{- if and (not .Values.forwarding.infra.splunk.insecure) .Values.forwarding.infra.splunk.caFile -}}
{{- $splunkCaFile := .Files.Get .Values.forwarding.infra.splunk.caFile }}
{{- if not $splunkCaFile -}}
{{- fail "Could not locate Splunk Certificate" }}
{{ end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openshift-logforwarding-splunk.fullname" . }}-infra-splunk
  labels:
    app.kubernetes.io/component: splunk
{{ include "openshift-logforwarding-splunk.labels" . | indent 4 }}
type: Opaque
data:
    splunk-ca.crt: {{ $splunkCaFile | b64enc }}
{{ end }}
