apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - log-forwarding-serviceaccount.yaml
  - log-forwarding-splunk-service.yaml
  - log-forwarding-splunk-configmap.yaml
  - log-forwarding-splunk-deployment.yaml
  - log-forwarding-instance.yaml
  - clusterlogging-instance.yaml
