kind: ConfigMap
apiVersion: v1
metadata:
  name: log-forwarding-splunk-config
  namespace: openshift-logging
data:
  splunk-insecure: "true"
  splunk-hostname: splunk.splunk.svc
  splunk-protocol: https
  splunk-index: openshift
  td-agent.conf: |

    <system>
      log_level "#{ENV['LOG_LEVEL'] || 'warn'}"
    </system>

    <source>
      @type  forward
      @id    input1
      port  24224

      <transport tls>
        cert_path /secret/fluentd/tls.crt
        private_key_path /secret/fluentd/tls.key
      </transport>

      <security>
        shared_key "#{ENV['SHARED_KEY'] }"
        self_hostname "#{ENV['HOSTNAME']}"
      </security>

    </source>

    <match **>
      @type splunk_hec
      protocol "#{ENV['SPLUNK_PROTOCOL'] || 'https'}"
      insecure_ssl "#{ENV['SPLUNK_INSECURE'] || 'true'}"
      hec_host "#{ENV['SPLUNK_HOST'] }"
      sourcetype "OCP}"
      source "#{ENV['CLUSTER_NAME'] || 'OCP'}"
      index "#{ENV['SPLUNK_INDEX'] || 'openshift'}"
      hec_port "#{ENV['SPLUNK_PORT'] || 8088 }"
      hec_token "#{ENV['SPLUNK_TOKEN'] }"
      host "#{ENV['NODE_NAME']}"
      <buffer>
        @type memory
        chunk_limit_records 100000
        chunk_limit_size 200m
        flush_interval 5s
        flush_thread_count 1
        overflow_action block
        retry_max_times 3
        total_limit_size 600m
      </buffer>
    </match>
