apiVersion: logging.openshift.io/v1alpha1
kind: LogForwarding
metadata:
  name: instance
  namespace: openshift-logging
spec:
  disableDefaultForwarding: true
  outputs:
    - endpoint: "log-forwarding-splunk:24224"
      name: log-forwarding-splunk
      type: forward
      secret:
        name: log-forwarding-splunk
    - endpoint: "elasticsearch.openshift-logging.svc:9200"
      name: elasticsearch
      secret:
        name: fluentd
      type: elasticsearch
  pipelines:
    - inputSource: logs.app
      name: container-logs
      outputRefs:
        - elasticsearch
        - log-forwarding-splunk
    - inputSource: logs.infra
      name: infra-logs
      outputRefs:
        - elasticsearch
    - inputSource: logs.audit
      name: audit-logs
      outputRefs:
        - elasticsearch
